apiVersion: v1
kind: Service
metadata:
  name: simple-service
  namespace: my-custome-namespace
spec:
  selector:
    app: simple-deployment
  ports:
    - protocol: TCP
      port: 8183
      targetPort: 80
